# Generated by Django 4.0.4 on 2022-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_rename_recipe_weight_food_amount_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='kcal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='kcal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='weight',
            field=models.FloatField(),
        ),
    ]
