# Generated by Django 4.0.3 on 2022-05-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='born_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='calcul_age',
        ),
    ]
