# Generated by Django 4.0.4 on 2022-05-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_basalmetabolism'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasalMetabolism',
        ),
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.CharField(choices=[('office job, no activities', 'office job, no activities'), ('office job, training twice per week', 'office job, training twice per week'), ('office job, training 3-4 times per week', 'office job, training 3-4 times per week'), ('office job, training 6 times per week', 'office job, training 6 times per week'), ('manual job, training 3-4 times per week', 'manual job, training 3-4 times per week'), ('manual job, training 6 times per week', 'manual job, training 6 times per week')], default='office job, no activities', help_text='How active are you?', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='target',
            field=models.CharField(choices=[('I would like lose weight', 'I would like lose weight'), ('I just want be as fit as I am', 'I just want be as fit as I am'), ('I want gain muscles/weight', 'I want gain muscles/weight')], default='I would like lose weight', help_text='What is your target?', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('0', 'Mr.'), ('1', 'Mrs.'), ('2', 'Ms.')], max_length=5),
        ),
    ]
