# Generated by Django 4.0.3 on 2022-05-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_age_alter_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.CharField(choices=[('office job, no activities', 'office job, no activities'), ('office job, training twice per week', 'office job, training twice per week'), ('office job, training 3-4 times per week', 'office job, training 3-4 times per week'), ('office job, training 6 times per week', 'office job, training 6 times per week'), ('manual job, training 3-4 times per week', 'manual job, training 3-4 times per week'), ('manual job, training 6 times per week', 'manual job, training 6 times per week')], default='office job, no activities', max_length=255),
        ),
    ]
