# Generated by Django 4.0.3 on 2022-05-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='target',
            field=models.CharField(choices=[('I would like lose weight', 'I would like lose weight'), ('I just want be as fit as I am', 'I just want be as fit as I am'), ('I want gain muscles/weight', 'I want gain muscles/weight')], default='I would like lose weight', max_length=255),
        ),
    ]
