# Generated by Django 4.0.3 on 2022-05-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created', models.DateField()),
                ('ingredients', models.CharField(max_length=256)),
                ('kcal', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('food', models.ManyToManyField(related_name='recipes', to='food.food')),
            ],
        ),
    ]
