# Generated by Django 4.0.2 on 2022-05-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='food',
            field=models.ManyToManyField(related_name='recipes', to='food.Food'),
        ),
    ]
