# Generated by Django 4.0.4 on 2022-05-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMICounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
