# Generated by Django 4.0.4 on 2022-05-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_recipe_food'),
        ('food', '0007_delete_blogpost_alter_blog_image'),
    ]

    operations = [
    ]
