# Generated by Django 4.0.3 on 2022-05-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_recipe_food'),
        ('food', '0008_alter_blog_image'),
    ]

    operations = [
    ]
