# Generated by Django 4.0.4 on 2022-06-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='kcal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(),
        ),
    ]
