# Generated by Django 4.0.4 on 2022-05-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='food',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='food.Amount', to='food.food'),
        ),
    ]
