# Generated by Django 4.0.4 on 2022-06-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
