# Generated by Django 4.0.3 on 2022-05-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_height_user_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('0', 'Mr.'), ('1', 'Mrs.'), ('2', 'Ms.')], max_length=5),
        ),
    ]
